spring:
  application:
    name: digibank
  config:
    import: classpath:env.properties
  liquibase:
    change-log: classpath:/db/changelog/master.xml

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  frontend:
    url: ${FRONTEND_BASE_URL}

server:
  port: ${SERVER_PORT}
